### ISSUE TITLE
[Litmus] Test ISA-DEP-WR-ADDR failed in Litmus 7.56.3.

### ISSUE THREAD

**Issue by Sevwood** [herd/herdtools7#758] opened 2024-01-17 09:22 UTC
Hi herdtools devs:

I just updated my Litmus version from 7.56 to 7.56.3.
However, while running Litmus on my machine, a test called ISA-DEP-WR-ADDR failed with the following message:
```
Failure: ISA-DEP-WR-ADDR, ???
```
After reviewing its source code, it seems like a function called idx_addr has been added to test ISA-DEP-WR-ADDR while compiling with Litmus 7.56.3.
```
static int idx_addr(ctx_t *_a,int _i,void *v_addr) {
  if (v_addr == NULL) { return 0;}
  else if (v_addr == (void *)&(_a->y[_i])) return 1;
  else if (v_addr == (void *)&(_a->x[_i])) return 2;
  else { fatal("ISA-DEP-WR-ADDR, ???"); return -1;}
}
```
It is strange to see this function in test ISA-DEP-WR-ADDR because the value of v_addr in this test is 0 or 1 but not an address.
May I ask is this function idx_addr in test ISA-DEP-WR-ADDR reasonable?
And if it is not reasonable, then how can I solve it?

Thank you
Sev

**Comment by maranget** [comment] 2024-01-17 09:50
Hi @Sevwood, thanks for your report.

Would you share the ISA-DEP-WR-ADDR test with us? This would help a lot.

**Comment by Sevwood** [comment] 2024-01-17 09:57
> Hi @Sevwood, thanks for your report.
> 
> Would you share the ISA-DEP-WR-ADDR test with us? This would help a lot.

Hi @maranget 

Sure, the attached zip contains two ISA-DEP-WR-ADDR.c generated by litmus 7.56.3 and litmus 7.56.

[ISA-DEP-WR-ADDR.zip](https://github.com/herd/herdtools7/files/13961455/ISA-DEP-WR-ADDR.zip)

Thank you,
Sev.

**Comment by maranget** [comment] 2024-01-17 10:04
Thanks, the litmus would help me even more.

**Comment by Sevwood** [comment] 2024-01-17 10:24
> Thanks, the litmus would help me even more.

Hi @maranget 

Do you mean you need my litmus7 built by herdtools7?

Thank you,
Sev.

**Comment by maranget** [comment] 2024-01-17 10:35
Looking at  the C files,  litmus 7.56.3 found that register x5 of thread P0 holds an addresse, while litmus 7.56 did not.

Indeed this register holds an adress as P0 code includes one store and one load instruction whose effective address is 0(x5). Having the litmus test at hand would help me understand where is 0:x5 coming from. Moreover, if the test has been produced by one of herdtools generators, it may be that the generator is buggy, So having the whole story would help to understand where the problem is.

**Comment by maranget** [comment] 2024-01-17 11:13
Ok I found the the test 
[ISA-DEP-WR-ADDR](https://github.com/herd/herdtools7/files/13962126/ISA-DEP-WR-ADDR.litmus.txt).
```
RISCV ISA-DEP-WR-ADDR
(* SC-W to R addr dependency through result register *)
{
0:x5=x; 0:x10=y;
1:x6=y; 1:x9=x;
}
 P0               | P1            ;
 ori x6,x0,1      | ori x5,x0,1   ;
 lr.w x7,0(x5)    | sw x5,0(x6)   ;
 sc.w x8,x6,0(x5) | fence rw,rw   ;
 xor x9,x8,x8     | lw x8,0(x9)  ;
 add x11,x10,x9   |               ;
 lw x5,0(x11)     |               ;
exists
(x=1 /\ 0:x5=0 /\ 1:x8=0)
```

This test confuses litmus because the register `0:x5` is used both as an address and as a scalar. It can be fixed by renaming the "scalar" `x5` into `x1` as follows:
``
RISCV ISA-DEP-WR-ADDR
(* SC-W to R addr dependency through result register *)
{
0:x5=x; 0:x10=y;
1:x6=y; 1:x9=x;
}
 P0               | P1            ;
 ori x6,x0,1      | ori x5,x0,1   ;
 lr.w x7,0(x5)    | sw x5,0(x6)   ;
 sc.w x8,x6,0(x5) | fence rw,rw   ;
 xor x9,x8,x8     | lw x8,0(x9)  ;
 add x11,x10,x9   |               ;
 lw x1,0(x11)     |               ;
exists
(x=1 /\ 0:x1=0 /\ 1:x8=0)
```

**Comment by Sevwood** [comment] 2024-01-17 12:19
Thank you so much, I will try this solution later.

**Comment by maranget** [comment] 2024-01-17 13:35
Notice that litmus7 could have issued a warning and even reject the test because the two underlying  types (int * and int)  have different sizes (64 and 32 bits).

**Closed by maranget** 2024-01-17 13:35 UTC
